config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  get 'articles/country'
  get 'articles/country_list'
  get 'articles/edit_country'
  get 'articles/resource'
  get 'articles/resource_list'
  get 'articles/category'
  get 'articles/category_list'
  get 'articles/update_country'
  get 'articles/add_country'
  get 'articles/delete_country'
  get 'articles/edit_resource'
  get 'articles/delete_resource'
  get 'articles/delete_category'
  get 'articles/add_resource'
  get 'articles/add_category'
  get 'articles/show_availresource'
  get 'articles/new_availresource'
  get 'articles/delete_availresource' 
  get 'articles/add_availresource'

  resources :articles
  resources :articletwos
  root 'welcome#index'

end

app/models/articletwo.rb
class Articletwo < ActiveRecord::Base
end

app/models/avail_resource.rb
class AvailResource < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def new
        @country_list = Country.all
        @resource_list = Resource.all
        @category_list = Category.all
    end

    def show
      @article = Article.find(params[:id])
    end

    def index
      @articles = Article.all
    end     


    def create
      save_params = Hash.new
      country = params[:country]
      resourcename = params[:resourcename]
      text = country + '-' + resourcename       

      save_params['title'] = text

      @category = Category.all
      categoryList = Array.new
      @category.each do |category|
        categoryList.push(category.categoryname)             
      end 
      new_category = []        

      for a_cat in categoryList
        if params.has_value?(a_cat)
            new_category.push(a_cat)
        end
      end        
            
      save_params['text'] = new_category.join('|')     

      puts save_params
      @article = Article.new(save_params)

      puts "Article params"
      puts @article      

      @article.save


      redirect_to @article
    end

    def edit
        @article = Article.find(params[:id])

       @my_val = @article.text.split('|')
       @my_val2 = @article.title.split('-')
       @my_val.concat(@my_val2)

       @country = Country.all
       @country_hash = Hash.new
       
       @country.each do |country|
        cname = country.countryname
        @country_hash[cname] = @my_val.include?cname
       end

        
       @resource  = Resource.all
       @resource_hash = Hash.new
        
       @resource.each do |resource|
        rname = resource.resourcename
        @resource_hash[rname] = @my_val.include?rname
       end 
       
       @category = Category.all
       @category_hash = Hash.new

       @category.each do |category|  
        catname = category.categoryname
        @category_hash[catname] = @my_val.include?catname
       end        

    end
       
    def update
      @article = Article.find(params[:id])

      save_params = Hash.new
      country = params[:country]
      resourcename = params[:resourcename]
      text = country + '-' + resourcename       

      save_params['title'] = text

      @category = Category.all
      category_list = Array.new
      @category.each do |category|
        category_list.push(category.categoryname)        
      end  
      new_category = []        

      for a_cat in category_list
        if params.has_key?(a_cat)
            new_category.push(a_cat)
        end
      end        
            
      save_params['text'] = new_category.join('|')     

      if @article.update(save_params)
        redirect_to @article
      else
        render 'edit'
      end    
    end   

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
     
      redirect_to articles_path
    end

    def delete_country
        @country = Country.find(params[:format])
        @country.destroy
        
        redirect_to new_article_path
    end


    def delete_resource
        @resource = Resource.find(params[:format])
        @resource.destroy

        redirect_to new_article_path
    end

    def delete_category
        @category = Category.find(params[:format])
        @category.destroy

        redirect_to new_article_path
    end

    def add_country
        #Add a country
        country_hash = Hash.new 
        input_hash = params['articles'] 
        country_hash['countryname'] = input_hash['title']
        @country = Country.new(country_hash)
        @country.save
        @country_list = Country.all
    end

    def country
    end

    def country_list
        #Add a country
        @country_list = Country.all
    end

    def resource
    end

    def add_resource
        #Add a resource
        resource_hash = Hash.new 
        input_hash = params['articles'] 
        resource_hash['resourcename'] = input_hash['title']
        @resource = Resource.new(resource_hash)
        @resource.save
        @resource_list = Resource.all

        redirect_to articles_resource_list_path
    end

    def resource_list
        @resource_list = Resource.all
    end
    
    def category
    end
  
    def add_category
        #Add a category
        category_hash = Hash.new 
        input_hash = params['articles'] 
        category_hash['categoryname'] = input_hash['title']
        @category = Category.new(category_hash)
        @category.save
        @category_list = Category.all
        
        redirect_to articles_category_list_path
    end
 
    def category_list
        @category_list = Category.all
    end

    def edit_country
        puts params
        @country = Country.find(params[:format])
        @countryname = @country.countryname
     end

    def udpate_country
        @country = Country.find(params[:format]) 
                   
    end

    def edit_resource
        @resource = Resource.find(params[:format])
        
    end

    def show_availresource
        @availresource = AvailResource.all
    end

    def new_availresource
        @availKeys = ['INDIAExceptionHandler', 'CHINAExceptionHandler', 'USAExceptionHandler', 'UnAvailableResources']
        @resource = Resource.all        

    end
    
    def add_availresource
        params_hash = Hash.new
        params_hash['key'] = params[:title]

        @resource = Resource.all
        selected_resource = []
        
        @resource.each do |resource|
            if params.has_key?(resource.resourcename)
                selected_resource.push(resource.resourcename)
            end
        end

        params_hash['value'] = selected_resource.join('|')
        puts params_hash
        @availresource = AvailResource.new(params_hash)
        @availresource.save

        redirect_to articles_show_availresource_path
    end 

    def delete_availresource
        @resource = AvailResource.find(params[:format])
        @resource.destroy

        redirect_to articles_show_availresource_path
    end
end

app/controllers/articletwos_controller.rb
class ArticletwosController < ApplicationController
   
    def new
    end
 
    def index
        @articletwos = Articletwo.all
    end

    def show
        @articletwos = Articletwo.find(params[:id])
    end

    def create
        
        params_hash = Hash.new
        articles_hash = params[:articletwos]
        params_hash['key'] = articles_hash[:title]
        params_hash['value'] = articles_hash[:text]

        @articletwo = Articletwo.new(params_hash)
        @articletwo.save
        redirect_to @articletwo
    end

    def edit
        @articletwo = Articletwo.find(params[:id])
    end 

    def update
        @articletwo = Articletwo.find(params[:id])
             
        params_hash = Hash.new
        articles_hash = params[:articletwo]
        params_hash['key'] = articles_hash[:key]
        params_hash['value'] = articles_hash[:value]
   
        if @articletwo.update(params_hash)
            redirect_to @articletwo
        else
            render 'edit'
        end
    end
   
    def destroy
        @article = Articletwo.find(params[:id])
        @article.destroy

        redirect_to articletwos_path
    end
 
end

app/helpers/articletwos_helper.rb
module ArticletwosHelper
end

app/views/articles/add_country.html.erb
<h1>Add new country</h1>

<table>
    <tr>
        <th>CountryName</th>
    </tr>

    <% @country_list.each do |country| %>
        <tr>
            <td><%= country.countryname %></td>
        </tr>
    <% end %>

</table>


<%= link_to 'Back', new_article_path %>

app/views/articles/category.html.erb
<h1 align="Center">Categories</h1>

<%= form_for :articles, method: "get", url: articles_add_category_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_area :title %>
    </p>

    <p>
        <%= f.submit :value => 'Add Category' %>
    </p>

<% end %>

<%= link_to 'Back', new_article_path %>
<%= link_to 'Category List', articles_category_list_path %>

app/views/articles/category_list.html.erb
<h1>List of category</h1>

<table>
    <tr>
        <th>CategoryName</th>
    </tr>

    <% @category_list.each do |category| %>
        <tr>
            <td><%= category.categoryname %></td>
        </tr>
    <% end %>

</table>


<%= link_to 'Back', new_article_path %>

app/views/articles/country.html.erb
<h1 align="center"> Countries</h1>

<%= form_for :articles, method: "get", url: articles_add_country_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_area :title %>
    </p>

    <p>
        <%= f.submit :value => 'Add Country' %>
    </p>

<% end %>

<%= link_to 'Back', new_article_path %>
<%= link_to 'Country List', articles_country_list_path %>

app/views/articles/country_list.html.erb
<h1>List of countries</h1>

<table>
    <tr>
        <th>CountryName</th>
    </tr>

    <% @country_list.each do |country| %>
        <tr>
            <td><%= country.countryname %></td>
        </tr>
    <% end %>

</table>


<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1 align="center">Editing Resource-Category Parameter</h1>
 
 <%= form_for :article, url: article_path(@article), method: :patch do |f| %>

   <br/> 
  
   <%= @country_hash.each do |key,value| %> 
    <%= radio_button_tag 'country', key, value %>
    <%= label_tag key %><br/>
   <% end %> 

     
   <br/>
   <%= @resource_hash.each do |key,value| %>
    <%= radio_button_tag 'resourcename', key, value %>
    <%= label_tag key %><br/>
   <% end %>

   <br/>  
   <%= @category_hash.each do |key,value| %> 
    <%= check_box_tag key, key, value %> 
    <%= label_tag key %><br/>
   <% end %> 

   <p>
    <%=f.submit "Save" %>
   </p>   
   
 <%end%>   
 <%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 align="Center">Resource-Category Ticketallocator  Parameters</h1>
 
<table>
   <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
   </tr>
              
   <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article)%></td>
      <td><%= link_to 'Edit', edit_article_path(article)%></td>
      <td><%= link_to 'Delete', article_path(article),method: :delete, data: {confirm: 'Are you sure?'} %></td>  
    </tr>
   <% end %>
</table>

<br/><%= link_to 'View Generic Parameters', articletwos_path %>
<br/><%= link_to 'View Available Resource Parameter', articles_show_availresource_path %>
<br/><%= link_to 'Add Resource-Category Parameter', new_article_path %>

app/views/articles/new.html.erb
<h1 align='center'>Add New Resource-Category Parameter</h1>

<%= form_tag(articles_path, method: "post") do %>

    <br/>
    <h3>Countries</h3> 
    <% @country_list.each do |country| %>
        <%= radio_button_tag(:country, country.countryname) %>
        <%= label_tag(:country, country.countryname) %>
        <%= link_to 'Delete', articles_delete_country_path(country), data: {confirm: 'Are you sure?'}%><br/>
    <% end %>

 
    <br/>
    <h3>Resources</h3>
    <% @resource_list.each do |resource| %>
        <%= radio_button_tag(:resourcename, resource.resourcename) %>
        <%= label_tag(:resourcename, resource.resourcename) %>
        <%= link_to 'Delete', articles_delete_resource_path(resource), data: {confirm: 'Are you sure?'}%><br/>
    <% end %>    

   
    <br/>
    <h3>Categories</h3>
    <% @category_list.each do |category| %>
        <%= check_box_tag(category.categoryname, value = category.categoryname) %>
        <%= label_tag(:category, category.categoryname) %>
        <%= link_to 'Delete', articles_delete_category_path(category), data: {confirm: 'Are you sure?'}%><br/>
    <% end %><br/>
 
    <%= submit_tag("Submit") %>

<%end%>
<br/><%= link_to 'Back', articles_path%>
<br/><%= link_to 'Add Country', articles_country_path%>
<br/><%= link_to 'Add Resource', articles_resource_path%>
<br/><%= link_to 'Add Category', articles_category_path%>

app/views/articles/new_availresource.html.erb
<h1 align='center'>Add New AvailResource Parameter</h1>

<%= form_tag(articles_add_availresource_path, method: "get") do %>
 <br/>
 <h3>Title</h3>
 <% @availKeys.each do |availkey| %>
    <%= radio_button_tag(:title, availkey) %>
    <%= label_tag(:title, availkey) %><br/>
 <% end %>   

 <br/>
 <h3>Resources</h3>
 <%@resource.each do |resource| %>
    <%= check_box_tag(resource.resourcename, value= resource.resourcename) %>
    <%= label_tag(:resource, resource.resourcename) %><br/>
 <% end %>  
 <%= submit_tag("Submit") %>   
    
<% end %>

app/views/articles/resource.html.erb
<h1 align ="center">Resources</h1>

<%= form_for :articles, method: "get", url: articles_add_resource_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_area :title %>
    </p>

    <p>
        <%= f.submit :value => 'Add Resource' %>
    </p>

<% end %>

<%= link_to 'Back', new_article_path %>
<%= link_to 'Resource List', articles_resource_list_path %>

app/views/articles/resource_list.html.erb
<h1>List of resources</h1>

<table>
    <tr>
        <th>ResourceName</th>
    </tr>

    <% @resource_list.each do |resource| %>
        <tr>
            <td><%= resource.resourcename %></td>
        </tr>
    <% end %>

</table>


<%= link_to 'Back', new_article_path %>

app/views/articles/show.html.erb
<h1>Resource-Category Parameter</h1>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
     
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>
<%= link_to 'Edit', edit_article_path %>

app/views/articles/show_availresource.html.erb
<h1>Available Resource  Parameter</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    </tr>
    <% @availresource.each do |availresource| %>
        <tr>
            <td><%= availresource.key %></td>
            <td><%= availresource.value %></td>
            <td><%= link_to 'Delete', articles_delete_availresource_path(availresource), method: :get, data: {confirm: "Are you sure?"}%></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Back', articles_path %>
<%= link_to 'Add AvailResource', articles_new_availresource_path %>

app/views/articles/update_country.html.erb
<h1>Country updated</h1>

app/views/articletwos/edit.html.erb
<h1>Editing Generic Config Parameter</h1>
 
 <%= form_for :articletwo, url: articletwo_path(@articletwo), method: :patch do |f| %>
   <p>
    <%= f.label :title %><br>
    <%= f.text_area :key %>
   </p>
                                                      
   <p>
    <%= f.label :text %><br>
    <%= f.text_area :value %>
   </p>
 
   <p>
    <%=f.submit "Save" %>
   </p>   
   
 <%end%>   
 <%= link_to 'Back', articletwos_path %>

app/views/articletwos/index.html.erb
<h1 align="center">Generic TicketAllocator  Parameters</h1>

<table>
   <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
   </tr>

   <% @articletwos.each do |article| %>
        <tr>
            <td><%= article.key %></td>
            <td><%= article.value %></td>
            <td><%= link_to 'Show', articletwo_path(article)%></td>
            <td><%= link_to 'Edit', edit_articletwo_path(article)%></td>
            <td><%= link_to 'Delete', articletwo_path(article),method: :delete, data: {confirm: 'Are you sure?'} %></td>  
        </tr>
   <% end %>
</table>

<br/><%= link_to 'View Resource-Category Parameters', articles_path %>
<br/><%= link_to 'Add new generic parameter', new_articletwo_path %>

app/views/articletwos/new.html.erb
<h1>Add  New Generic Config Parameter</h1>

<%= form_for :articletwos, url: articletwos_path do |f| %>
  <p>
      <%= f.label :title %><br>
      <%= f.text_area :title %>
  </p>
             
  <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
  </p>
                          
  <p>
      <%= f.submit :value => "Add Parameter" %>
  </p>
<% end %>

<%= link_to 'Back', articletwos_path%>

app/views/articletwos/show.html.erb
<h1>Generic Ticketallocator  Parameter</h1>

<p>
  <strong>Title:</strong>
  <%= @articletwos.key %>
</p>
     
<p>
  <strong>Text:</strong>
  <%= @articletwos.value %>
</p>

<%= link_to 'Back', articletwos_path %>
<%= link_to 'Edit', edit_articletwo_path %>